### ISSUE TITLE
google/clasp doesn't provider any new release to fix the vulnerabilities

### ISSUE THREAD

**Issue by noissefnoc** [noissefnoc/gas-fetch-releasenotes#4]
`node-forge` has vulnerabilities issue under 0.10.0 but there's dependency on `google/clasp` (via `google-auth-library` and `node-gtoken`) and there's no update on `google/clasp` for a year. So I can't resolve this problem.

See: https://github.com/google/clasp/issues/812 for more details.

if they don't provide new version, I'll try to build and release another approach.

**Comment by PopGoesTheWza** [comment]
If you need the latest version of `@google/clasp` it is avialalble on npm as `forked-clasp`

```shell
npm uninstall -g @google/clasp
npm install -g forked-clasp
```

**Comment by noissefnoc** [comment]
@PopGoesTheWza Thanks and I don't reply for a long time. I saw your comment on that issue (2.3.1 resolves is this issue). But there is 2.3.2 on npmjs.com (https://www.npmjs.com/package/@google/clasp/v/2.3.2) and it doesn't affect 2.3.1 change.

I create issue on google/clasp (https://github.com/google/clasp/issues/845) and I'll wait for a while.

**Comment by noissefnoc** [comment]
I hear this problem will be resolved next release. I open this issue until next release comes.

**Comment by noissefnoc** [comment]
This resolved with `2.4.0`.
